server.port=9000
spring.thymeleaf.cache=false

#Configuracion actuator
management.endpoints.web.exposure.include=*
management.endpoints.web.exposure.exclude=flyway
management.endpoint.health.show-details=ALWAYS
