insert into Vehiculo (modelo, precio) values ('Opel Astra GT', 38000);
insert into Vehiculo (modelo, precio) values ('Ford Focus ST', 35000);
insert into Vehiculo (modelo, precio) values ('BMW 320i', 47000);
insert into Vehiculo (modelo, precio) values ('Mercedes-Benz C-Class', 52000);
insert into Vehiculo (modelo, precio) values ('Audi A4', 46000);
insert into Vehiculo (modelo, precio) values ('Volkswagen Golf GTI', 42000);
insert into Vehiculo (modelo, precio) values ('Honda Civic Type R', 40000);
insert into Vehiculo (modelo, precio) values ('Toyota Corolla GR', 39000);
insert into Vehiculo (modelo, precio) values ('Hyundai i30 N', 37000);
insert into Vehiculo (modelo, precio) values ('Mazda 3 Turbo', 41000);
insert into Vehiculo (modelo, precio) values ('Kia Ceed GT', 36000);
insert into Vehiculo (modelo, precio) values ('Peugeot 308 GTi', 38000);
insert into Vehiculo (modelo, precio) values ('Renault Megane RS', 42000);
insert into Vehiculo (modelo, precio) values ('Seat Leon Cupra', 43000);
insert into Vehiculo (modelo, precio) values ('Alfa Romeo Giulia', 51000);
insert into Vehiculo (modelo, precio) values ('Jaguar XE', 55000);
insert into Vehiculo (modelo, precio) values ('Porsche Macan', 64000);
insert into Vehiculo (modelo, precio) values ('Land Rover Range Rover Evoque', 60000);
insert into Vehiculo (modelo, precio) values ('BMW X5', 75000);
insert into Vehiculo (modelo, precio) values ('Mercedes-Benz GLE', 80000);
insert into Vehiculo (modelo, precio) values ('Audi Q7', 72000);
insert into Vehiculo (modelo, precio) values ('Volkswagen Tiguan', 45000);
insert into Vehiculo (modelo, precio) values ('Chevrolet Equinox', 47000);
insert into Vehiculo (modelo, precio) values ('Honda CR-V', 38000);
insert into Vehiculo (modelo, precio) values ('Toyota RAV4', 39000);
insert into Vehiculo (modelo, precio) values ('Ford Escape', 40000);
insert into Vehiculo (modelo, precio) values ('Nissan Rogue', 43000);
insert into Vehiculo (modelo, precio) values ('Subaru Forester', 42000);
insert into Vehiculo (modelo, precio) values ('Mazda CX-5', 46000);
insert into Vehiculo (modelo, precio) values ('Hyundai Tucson', 44000);
insert into Vehiculo (modelo, precio) values ('Kia Sportage', 45000);
insert into Vehiculo (modelo, precio) values ('Peugeot 5008', 49000);
insert into Vehiculo (modelo, precio) values ('Renault Koleos', 48000);
insert into Vehiculo (modelo, precio) values ('BMW 330e', 52000);
insert into Vehiculo (modelo, precio) values ('Audi A6', 59000);
insert into Vehiculo (modelo, precio) values ('Mercedes-Benz E-Class', 65000);
insert into Vehiculo (modelo, precio) values ('Jaguar F-Pace', 70000);
insert into Vehiculo (modelo, precio) values ('Porsche Cayenne', 82000);
insert into Vehiculo (modelo, precio) values ('Tesla Model X', 90000);
insert into Vehiculo (modelo, precio) values ('Volvo XC90', 75000);
insert into Vehiculo (modelo, precio) values ('Toyota Highlander', 53000);
insert into Vehiculo (modelo, precio) values ('Chevrolet Traverse', 54000);
insert into Vehiculo (modelo, precio) values ('Ford Expedition', 56000);
insert into Vehiculo (modelo, precio) values ('Honda Pilot', 55000);
insert into Vehiculo (modelo, precio) values ('GMC Acadia', 57000);
insert into Vehiculo (modelo, precio) values ('Nissan Pathfinder', 59000);
insert into Vehiculo (modelo, precio) values ('Subaru Ascent', 58000);
insert into Vehiculo (modelo, precio) values ('Hyundai Palisade', 61000);
insert into Vehiculo (modelo, precio) values ('Kia Telluride', 62000);
insert into Vehiculo (modelo, precio) values ('Peugeot 3008', 51000);