server.port=9000
spring.thymeleaf.cache=false

#configuración H2
spring.datasource.url=jdbc:h2:mem:mydbtest
spring.jpa.hibernate.ddl-auto = create
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

#Mostrar operaciones SQL en log consola 
spring.jpa.show-sql=true

#Permitir acceso a la consola H2
spring.h2.console.enabled=true

